
= Title
= wollt ihr das bett in flamen sehen
                  
----
wollt ihr: do you want
das bett in flamen sehen: seeing the bed in flames
----

== meaning: do you want to see the bed in flames



= lyrics

== first take:

--------------------------------------------------------------------------------
wollt ihr das bett in flammen sehen
wollt ihr halt und tarhen und tergehn
ihr wollt och achteen !!!!!!!!!!!!!!!!!!!!!!!!
ihr wollt och acht das blood !!!!!!!!!!!!!!!!

Rammstein
Rammstein


ihr sel!!!!!!!!!!! auf !!!!!!!!!!!!!
ihr meind !!!!!!!!!!!!!!!!!!!!!!!!!
ihr glaub !!!!!!!!!!!!!!!!!!!!!!!!
doch wo kommen !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Rammstein
Rammstein

Rammstein


sex 
!!!!!!!!!
libe est kik   ???

sex 
!!!!!!!!!
libe est kik   ???

sex 
!!!!!!!!!
libe est kik   ???

sex 
!!!!!!!!!
libe est kik   ???

wollt ihr das bett in flammen sehen
wollt ihr halt und tarhen und tergehn
ihr wollt och achteen !!!!!!!!!!!!!!!!!!!!!!!!
ihr wollt och acht das blood !!!!!!!!!!!!!!!!

Rammstein
Rammstein

Rammstein
Rammstein

Rammstein
Rammstein

Rammstein
Rammstein

Rammstein
Rammstein

Rammstein
Rammstein
--------------------------------------------------------------------------------

== actual lyrics:

--------------------------------------------------------------------------------
    [Strophe 1]
Wollt ihr das Bett in Flammen sehen? <1>
Wollt ihr in Haut und Haaren untergehen? <2>

Ihr wollt doch auch den Dolch ins Laken stecken
Ihr wollt doch auch das Blut vom Degen lecken

    [Refrain]
[#l4]
Rammstein!
Rammstein!

    [Strophe 2]
[#l6]
Ihr seht die Kreuze auf dem Kissen
[#l7]
Ihr meint euch darf die Unschuld küssen
[#l8]
Ihr glaubt, zu töten wäre schwer
[#l9]
Doch wo kommen all die Toten her?

    [Refrain]
Rammstein!
Rammstein!
Rammstein!

    [Bridge]
Sex ist eine Schlacht
Liebe ist Krieg
Sex ist eine Schlacht, ja
Liebe ist Krieg
Sex ist eine Schlacht
Liebe ist Krieg
Sex ist eine Schlacht, ja
Liebe ist Krieg

    [Strophe 1]
Wollt ihr das Bett in Flammen sehen?
Wollt ihr in Haut und Haaren untergehen?
Ihr wollt doch auch den Dolch ins Laken stecken
Ihr wollt doch auch das Blut vom Degen lecken

    [Refrain]
Rammstein!
Rammstein!
Rammstein!
Rammstein!

    [Outro]
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!
Rammstein!

--------------------------------------------------------------------------------

= analysis:

== <1> Wollt ihr in Haut und Haaren untergehen?
[%hardbreaks]
die Haut    = skin
das Haar    = hair
die+ Haare  = hairs


'in Haut und Haaren' -> in skin and hair

it has a general meaning of: compeletly, entiraly

[%hardbreaks]
untergehen 
gehen : going
untergehen : going down
mostly meaning destruction

es geht unter -> it gets destroyed


=== : do you want to be compeletely destroyed?


== <2> Ihr wollt doch auch den Dolch ins Laken stecken
[%hardbreaks]

stecken = to put/stick/insert

[%hardbreaks]
der Dolck = dagger
das Laken = bed sheet


=== : you also wnat to stck the dagger into the sheets



== <<l3, Ihr wollt doch auch das Blut vom Degen lecken>>
[%hardbreaks]

der Degen = sword
vom = von dem = 'from the'
vom Degen = from the sword

lecken : to lick


=== : you also want to lick the blood from the sword 




== <<l4,Rammstein! Rammstein!>>
[%hardbreaks]



[%header]
|===
|der Rammstein |colliding stone, hitting stone 

|Rammen
|to ramm, to collide with

|der Stein
|stone
|===



== <<l5, Ihr seht die Kreuze auf dem Kissen>>

[%hardbreaks]
das Kreuz   = cross
die+ Kreuze = crosses


das kissen = pillow


=== : you see the crossese on the pillow



== <<l6, Ihr meint euch darf die Unschuld küssen>>
[%hardbreaks]

[%header]
[options="header"]
|===
|meinen 	| to mean, to think to belive

|ich        | meine
|du         | meinst
|er/sie/es  | meint
|wir        | meinen
|ihr        | meint
|Sie        | meinen
|===


[%hardbreaks]
euch : you
darf : may

[%hardbreaks]
die Unschuld = innocence, verginity
küssen : to kiss 

=== : you think that innocance might kiss you

== <<l7, Ihr glaubt, zu töten wäre schwer>>

|====
|glauben 	| to believe, to think

|ich       	| glaube
|du        	| glaubst
|er/sie/es 	| glaubt
|wir       	| glauben
|ihr       	| glaubt
|Sie       	| glauben
|====

[%hardbreaks]

zu töten = to kill
töten : to kill

wäre : would be
sein : to be

schwer = difficult, hard

[%hardbreaks]
'zu + infinitive' -> to do something
'zu töten' -> to kill


=== : you think: killing would be difficult


== Doch wo kommen all die Toten her?

wo : where

herkommen : comming from


[%hardbreaks]
tot = (adj) dead
der Tote    = dead man
die Tote    = dead woman
die+ Toten  = the dead 


=== : but/afterall where do all the dead come from?



== <<l8, Sex ist eine Schlacht, Liebe ist Krieg>>

[%hardbreaks]
die Shlacht = battle
der krieg   = war

=== : sex is a battle, love is war
